<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LT14-HAH1-IND" failures="1" tests="1" name="com.webdriver.tests.TestBrokenLinks" time="9.195" errors="0" timestamp="2021-08-29T23:31:49 IST" skipped="0">
  <testcase classname="com.webdriver.tests.TestBrokenLinks" name="TestLinks" time="9.195">
    <failure message="The following asserts failed:
	301 expected [true] but found [false],
	https://rahulshettyacademy.com/brokenlink is BROKEN expected [false] but found [true],
	404 expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
301 expected [true] but found [false],
https://rahulshettyacademy.com/brokenlink is BROKEN expected [false] but found [true],
404 expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.webdriver.tests.TestBrokenLinks.TestLinks(TestBrokenLinks.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestLinks -->
  <system-out>
    <![CDATA[In onTestStart(ITestResult arg) ===== :class com.listeners.hooks.Listener

In before method Invocation :class com.listeners.hooks.Listener

Before executingTestBrokenLinks.TestLinks()[pri:0, instance:com.webdriver.tests.TestBrokenLinks@446293d]

In after method Invocation :class com.listeners.hooks.Listener

After executing :TestBrokenLinks.TestLinks()[pri:0, instance:com.webdriver.tests.TestBrokenLinks@446293d]

In onTestFailure(ITestResult result) ===== :class com.listeners.hooks.Listener
]]>
  </system-out>
</testsuite> <!-- com.webdriver.tests.TestBrokenLinks -->
